- hosts: all
  user: ubuntu
  become: yes
  tasks:
    - name: Adjust ubuntu user
      user:
        name: ubuntu
        groups: root,ubuntu,docker,sudo
        append: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa

    - name: Set authorized key for user ubuntu copying it from current user
      shell: |
        grep 'ansible-generated' /home/ubuntu/.ssh/authorized_keys || \
        cat /home/ubuntu/.ssh/id_rsa.pub | tee -a /home/ubuntu/.ssh/authorized_keys

    - name: Install Python3 related packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - python3
        - python3-pip
        - python3-setuptools
        - build-essential

    - name: Install docker-compose
      become: yes
      shell: |
        pip install -U pip
        pip install docker-compose
