- hosts: all
  user: ubuntu
  become: yes
  tasks:
    - name: Adjust ubuntu user
      user:
        name: ubuntu
        groups: root,ubuntu,docker,sudo
        append: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa

    - name: Set authorized key for user ubuntu copying it from current user
      shell: |
        grep 'ansible-generated' /home/ubuntu/.ssh/authorized_keys || \
        cat /home/ubuntu/.ssh/id_rsa.pub | tee -a /home/ubuntu/.ssh/authorized_keys

    - name: Install Python3 related packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - python3
        - python3-pip
        - python3-setuptools
        - build-essential
        - htop
        - vim
        - git

    - name: Install pip3
      become: yes
      shell: |
        pip3 install -U pip requests || true

    - name: Install docker-compose
      become: yes
      shell: |
        pip3 install docker-compose docker || true

    - name: Launch kluczyk docker container
      shell: |
        docker kill kluczyk
        docker pull s4ros/kluczyk:latest
        docker run -d --rm --name kluczyk \
        -e FLASK_PORT=80 \
        -v /home/ubuntu/.ssh:/root/.ssh:ro \
        -p 80:80 \
        s4ros/kluczyk:latest

    # - name: Download WordPress tar.gz archive
    #   get_url:
    #     url: https://pl.wordpress.org/latest-pl_PL.tar.gz
    #     dest: /home/ubuntu/wordpress.tar.gz
    #     mode: '0644'

    - name: Enable SSH Port forwarding
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: .*AllowTcpForwarding
        line: AllowTcpForwarding yes

    - name: Enable SSH Agent forwarding
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: .*AllowAgentForwarding
        line: AllowAgentForwarding yes

    - name: restart sshd
      become: yes
      shell: service ssh restart
